dimforge/rapier

examples3d/all_examples3.rs
examples3d/debug_trimesh3.rs
src/geometry/contact_generator/trimesh_shape_contact_generator.rs
src/geometry/polyhedron_feature3d.rs
src/lib.rs

This fixes:
- A divide-by-zero when the normal of a polygonal feature is perfectly orthogonal to a separating axis.
- A mixup in collider references when the trimesh's collider is input in the second position of the `trimesh_shape_contact_generator`.

Fix NaN caused by the collision-detection between a vertical triangle and a cuboid.

---

README.md

`rapier` is published with `rapier2d` and `rapier3d` variants, so this change adds badges for both and links to the correct pages.

Fix crates.io Badges

---

examples3d/debug_boxes3.rs
src/geometry/wquadtree.rs

The WQuadtree construction function would overflow the stack whenever more than 4 AABBs with the same center are provided. Moreover, this same configuration would cause a subtraction underflow.
This PR fixes both bugs.

Fix stack overflow caused by the WQuadtree

---

src/dynamics/rigid_body.rs
src/geometry/collider.rs

With this PR, we allow one user-defined `u128` integer to be associated to each collider and rigid-bodies. The typical use-case is to store an entity ID from an ECS-based game engine. More generally, it can store and index to an external data vector. In addition, this is serializable in case the user needs it.

Add a 128-bits user-data attached to colliders and rigid-bodies.

---

build/rapier2d/Cargo.toml
build/rapier3d/Cargo.toml
examples2d/all_examples2.rs
examples2d/collision_groups2.rs
examples3d/all_examples3.rs
examples3d/collision_groups3.rs
src/geometry/collider.rs
src/geometry/contact.rs
src/geometry/contact_generator/contact_generator.rs
src/geometry/contact_generator/heightfield_shape_contact_generator.rs
src/geometry/contact_generator/trimesh_shape_contact_generator.rs
src/geometry/interaction_groups.rs
src/geometry/mod.rs
src/geometry/narrow_phase.rs
src/pipeline/query_pipeline.rs
src_testbed/engine.rs
src_testbed/testbed.rs

Fix #2 
This add the support for collision filtering based on bit masks (often known as collision groups, collision masks, or collision layers in other physics engines). Each collider has two groups:
- The `collision_groups` for filtering what pair of colliders should have their contacts computed by the narrow-phase. This filtering happens right after the broad-phase, before the narrow phase.
- The `solver_groups` for filtering what pair of colliders should have their contact forces computed. This filtering happens right after the narrow-phase, before the constraints solver
The `collision_groups` is what will probably be used most of the time as it allows preventing some specific pairs of collisions from being in contact at all.
The `solver_groups` is a bit different because it will allow …

Add collision filtering based in bit masks

---

src/geometry/contact.rs
src/geometry/mod.rs
src/geometry/narrow_phase.rs
src/geometry/user_callbacks.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src_testbed/testbed.rs

Fix #3
Fix #15 
This PR adds two traits `CollisionPairFilter` and `ProximityPairFilter` that allows user-defined logic for determining if two colliders/sensors are allowed to interact, as discussed in #3 
If these filters are set by the user (i.e. passed to the `PhysicsPipeline::step` method), then they replace the predefined filtering logic which consists of preventing contact computation between two non-dynamic bodies (the collision-groups on the other hands are still taken into account). That way, it is possible for the user to enable  contacts and proximity between two non-dynamic bodies to be computed, as suggested in #15 
Finally, the `CollisionPairFilter` returns a `SolverFlags` bitmask that will be used by the constraints solver to handle the contact manifolds for this collision …

Added user-implementable traits for collision/proximity pair filtering.

---

src/data/hashmap.rs
src/data/maybe_serializable_data.rs
src/data/mod.rs
src/geometry/broad_phase_multi_sap.rs
src/geometry/contact.rs
src/geometry/contact_generator/contact_dispatcher.rs
src/geometry/contact_generator/contact_generator.rs
src/geometry/contact_generator/contact_generator_workspace.rs
src/geometry/contact_generator/heightfield_shape_contact_generator.rs
src/geometry/contact_generator/mod.rs
src/geometry/contact_generator/pfm_pfm_contact_generator.rs
src/geometry/contact_generator/serializable_workspace_tag.rs
src/geometry/contact_generator/trimesh_shape_contact_generator.rs
src/geometry/narrow_phase.rs
src/geometry/polyhedron_feature3d.rs
src/utils.rs

When restarting the same simulation from two distinct snapshots, the two states would reach different states because some contact generators rely on cached data which need to be serialized too in order to guarantee determinism. So this PR adds serialization of contact generator contexts.

Fix simulation reaching different states when started from different snaphots

---

src/data/graph.rs
src/data/maybe_serializable_data.rs
src/data/pubsub.rs
src/dynamics/joint/joint.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_set.rs
src/geometry/broad_phase_multi_sap.rs
src/geometry/collider.rs
src/geometry/collider_set.rs
src/geometry/contact.rs
src/geometry/contact_generator/contact_generator_workspace.rs
src/geometry/contact_generator/heightfield_shape_contact_generator.rs
src/geometry/contact_generator/pfm_pfm_contact_generator.rs
src/geometry/contact_generator/trimesh_shape_contact_generator.rs
src/geometry/interaction_graph.rs
src/geometry/narrow_phase.rs
src/geometry/polyhedron_feature3d.rs
src/geometry/proximity.rs
src/pipeline/query_pipeline.rs

Fix #53 
This makes everything clonable, except for the `PhysicsPipeline` because it is not worth cloning (since it only contains temporary data).

Allow cloning all the physics components worth cloning

---

examples2d/all_examples2.rs
examples3d/all_examples3.rs
examples3d/debug_infinite_fall3.rs
src/geometry/broad_phase_multi_sap.rs

After the changes made by #30, some workspace data were serialized. This PR skips the serialization of these workspace data since this does not affect determinism.

Sap serialization: skip cache data

---

src/dynamics/rigid_body.rs

Add boolean parameter to rigid body methods as discussed in #5 
Closes #5

Add wake_up parameter to rigidbody methods

---

CHANGELOG
examples2d/add_remove2.rs
examples2d/platform2.rs
examples3d/add_remove3.rs
examples3d/damping3.rs
examples3d/platform3.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_set.rs
src/dynamics/solver/parallel_island_solver.rs
src/dynamics/solver/position_solver.rs
src/geometry/collider_set.rs
src/geometry/shape.rs
src/pipeline/query_pipeline.rs
src_testbed/box2d_backend.rs
src_testbed/nphysics_backend.rs
src_testbed/physx_backend.rs
src_testbed/testbed.rs

This is inspired by the discussion we had in #5 
This adds a boolean as a parameter to the methods for:
- collider removal;
- setting the rigid-body velocity.
- setting the rigid-body position.
This also add the ability to create a rigid-body that is initialized asleep.
This is a breaking change because the `linvel, angvel` and `position` fields of `RigidBody` are no longer public (I added methods to access them instead).

Add more explicit parameters to wake-up a rigid-body

---

README.md

Replace the Travis CI badge with the GitHub Actions CI badge

Replace build badge on README

---

examples3d/heightfield3.rs
examples3d/trimesh3.rs
src/geometry/waabb.rs

I tried to run Rapier on one of the new Mac Mini equipped with an Apple M1 processor. The physics engine itself builds and runs correctly, however the testbed needs some changes on winit and glutin in order to work properly (we just have to wait for the proper fixes to be released upstream).
Anyways, I ran the Rapier demos (with the `enhanced-determinism` feature enabled) on the Apple M1 and my desktop with an AMD Ryzen 9 3900X and found out there were some divergences between the states of the simulations when triangle meshed and heightfield were involved.
These divergences are fixed by this PR.
This means that once this PR lands, Rapier will be able to output the exact same simulation on two different machines where one of them is an ARM processor (Apple M1) and the other is an X86 …

Fix cross-platform determinism on the Apple M1 processor

---

examples3d/all_examples3.rs
examples3d/fountain3.rs
examples3d/heightfield3.rs
examples3d/joints3.rs
src/data/coarena.rs
src/data/mod.rs
src/dynamics/rigid_body_set.rs
src/geometry/collider.rs
src/geometry/collider_set.rs
src/geometry/interaction_graph.rs
src/geometry/narrow_phase.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src_testbed/testbed.rs

Fix #56 
This PRs will allow the user to retrieve:
- All the contacts/proximities involving one specific collider handle.
- The contacts/proximity information for one specific pair of collider handles.
In order to achieve this, one significant internal change was made: the interaction graph IDs are no longer stored in the `Collider`. Instead, they are stored by the narrow-phase directly. This is great because it decouples things a little more. However this adds a few indirection at some places when browsing the contact graph in needed. So we need to see if this has any notable effect on performance.

Allow access to contact information

---

examples3d/all_examples3.rs
examples3d/debug_add_remove_collider3.rs
examples3d/debug_dynamic_collider_add3.rs
examples3d/debug_rollback3.rs
examples3d/platform3.rs
src/dynamics/mod.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_set.rs
src/dynamics/solver/parallel_island_solver.rs
src/dynamics/solver/position_solver.rs
src/geometry/broad_phase_multi_sap.rs
src/geometry/collider.rs
src/geometry/collider_set.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src_testbed/engine.rs
src_testbed/physx_backend.rs

With this PR we detect when the user modified the positions of rigid-bodies so we can update their collider at the beginning of the timestep. This will also update the position of static and kinematic bodies properly. This will likely fix https://github.com/dimforge/bevy_rapier/issues/14

Track some user-initiated rigid-body modifications

---

CHANGELOG
examples2d/all_examples2.rs
examples2d/locked_rotation2.rs
examples2d/platform2.rs
examples3d/all_examples3.rs
examples3d/locked_rotation3.rs
src/dynamics/rigid_body.rs
src_testbed/box2d_backend.rs
src_testbed/nphysics_backend.rs
src_testbed/testbed.rs

Locking rotations isn't so easy right now: one needs to set the principal inertia of the rigid-body to zero **after** all the colliders has been attached to it. This can be annoying to do, especially when using an ECS like Bevy's (see https://github.com/dimforge/bevy_rapier/issues/9).
This PR introduces a few changes to make this much easier: it allows the user to specify, at construction time, if a rigid-body should ignore some contributions a collider would make to its mass properties. This allows making rotations along some coordinate axes, or all translations, behave in a kinematic way (i.e. only controlled by the user, immune to forces).
For convenience, there are the new `RigidBodyBuilder::lock_rotations` and `RigidBodyBuilder::lock_translations` that hide these details from the …

Add a more convenient way of locking the rotations (or translations) of a rigid-body

---

src_testbed/lib.rs
src_testbed/physics/mod.rs
src_testbed/plugin.rs
src_testbed/testbed.rs

Mainly adds public constructors to PhysicsState & PhysicsSnapshot.
Also moves PhysicsState & PhysicsSnapshot  & PhysicsEvents to their own module.
I mainly need this for the run harness work (only the public new's). If you'd prefer to keep it within testbed, I can change this back.

Extract Physics into module, make new public

---

.github/workflows/rapier-ci-bench.yml

Currently, the `send-bench-message` CI workflow will always fail on pull-requests originating from forks. This is caused by the fact that forks PRs don't have access to secrets. In this PR, we switch to `pull_request_target` as it should give (safely) access to secrets: https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/
I will make another PR after this one to check that this change actually works.

CI: use trigger the bench message workfrow on a pull_request_target instead of pull_request

---

.github/workflows/rapier-ci-bench.yml

It turned out that #90 did not really work as expected (and is un-testable without merging on master because of the way `pull_request_target` works). The changes introduced in this PR have been tested on a separate repo and should work. After merging this I will rebase #91 to see if it actually works.

Fix CI bench message emission for fork PRs.

---

src/dynamics/joint/joint_set.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_set.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/revolute_position_constraint.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint_wide.rs
src/geometry/broad_phase_multi_sap.rs
src/geometry/collider.rs
src/geometry/collider_set.rs
src/geometry/interaction_graph.rs
src/geometry/narrow_phase.rs
src/lib.rs
src/pipeline/physics_pipeline.rs

I did a quick pass fixing some things that clippy complained about. Nothing major. I there is anything you disagree with I am happy to revert.

Make clippy a bit happier

---

build/rapier2d-f64/Cargo.toml
build/rapier2d/Cargo.toml
build/rapier3d-f64/Cargo.toml
build/rapier3d/Cargo.toml
src/data/mod.rs
src/geometry/contact_pair.rs
src_testbed/testbed.rs

Solver contacts don't need to be serialized in order to preserve determinism after deserialization, so they are now skipped by serde.

Don't serialize solver contacts + remove erased-serde dependency.

---

src/dynamics/rigid_body.rs
src/dynamics/solver/island_solver.rs
src/dynamics/solver/parallel_island_solver.rs
src/dynamics/solver/velocity_solver.rs
src/pipeline/physics_pipeline.rs

Closes https://github.com/dimforge/rapier/issues/97
A ball bouncing on a plane with restitution=1 now perfectly conserves energy to within machine precision (within ~1e-7 per bounce).
Instead of applying accelerations from gravity and external forces
as a separate step, this PR switches to applying them in the velocity solver.

Apply accelerations during velocity solver

---

src/geometry/interaction_groups.rs

Add a missing word and a bit of whitespace

Fix a small documentation typo on InteractionGroups

---

src/geometry/narrow_phase.rs
src/geometry/pair_filter.rs

This makes it easy to write custom filters based on the handles.
For instance, a user can add pairs of `ColliderHandle`s into a `HashSet` (or `Coarena`) and do a lookup in a `ContactPairFilter` to easily (if maybe not efficiently) disable collisions between pairs of colliders.
The same could be accomplished by using the `user_data: u128` field of the `Collider`, but it would be less ergonomic, and also with this PR that `user_data` space can be saved for more important things.

Add ColliderHandle:s to PairFilterContext

---

src/dynamics/integration_parameters.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_wide.rs
src/dynamics/solver/velocity_ground_constraint.rs
src/dynamics/solver/velocity_ground_constraint_wide.rs
src/geometry/contact_pair.rs

If a contact is new (previous impulse = 0), then we treat it as bouncy (respecting restitution). If the contact is old we treat it as resting.
This allows us to remove the `restitution_velocity_threshold` parameter.
Special cases:
* `restitution <= 0` is always treated as resting
* `restitution >= 1` is always treated as bouncing
A 0.9 restitution ball bouncing on ground with the same (very high) restitution.
Previously an arbitrary `restitution_velocity_threshold` cutoff led to an abrupt end to bounces:
Bounces keep going up to nyquist limit, into a smooth transition to rest:

Split bouncy and resting contacts (take 2)

---

Cargo.toml
examples3d/joints3.rs
src/dynamics/integration_parameters.rs
src/dynamics/joint/ball_joint.rs
src/dynamics/joint/fixed_joint.rs
src/dynamics/joint/generic_joint.rs
src/dynamics/joint/joint.rs
src/dynamics/joint/mod.rs
src/dynamics/joint/prismatic_joint.rs
src/dynamics/joint/revolute_joint.rs
src/dynamics/joint/spring_model.rs
src/dynamics/mod.rs
src/dynamics/solver/interaction_groups.rs
src/dynamics/solver/joint_constraint/ball_velocity_constraint.rs
src/dynamics/solver/joint_constraint/generic_position_constraint.rs
src/dynamics/solver/joint_constraint/generic_position_constraint_wide.rs
src/dynamics/solver/joint_constraint/generic_velocity_constraint.rs
src/dynamics/solver/joint_constraint/generic_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/joint_constraint.rs
src/dynamics/solver/joint_constraint/joint_position_constraint.rs
src/dynamics/solver/joint_constraint/mod.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/revolute_position_constraint.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint_wide.rs
src/lib.rs
src_testbed/nphysics_backend.rs
src_testbed/physx_backend.rs

This adds motors to the prismatic, revolute, and ball joints. The motor acts as a spring-like constraint, configurable as described in #87. As such, it is possible to give the motor a target velocity as well as a target position.
Multiple spring-like equations (velocity-based, acceleration-based, or force-based) can be chosen by the user in a per-joint basis.
The `joint3` demo has been updated to add motorized joint examples.
This PR also includes some preliminary work on a generic 6DoF joint as suggest in #87. However it's not implemented in a very satisfying way yet so its sources are commented out right now.
Fix #87

Add joint motors

---

examples2d/all_examples2.rs
examples2d/damping2.rs
examples2d/one_way_platforms2.rs
examples3d/all_examples3.rs
examples3d/damping3.rs
examples3d/fountain3.rs
examples3d/one_way_platforms3.rs
src/dynamics/rigid_body_set.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_wide.rs
src/dynamics/solver/velocity_ground_constraint.rs
src/dynamics/solver/velocity_ground_constraint_wide.rs
src/geometry/collider.rs
src/geometry/contact_pair.rs
src/geometry/mod.rs
src/geometry/narrow_phase.rs
src/geometry/pair_filter.rs
src/pipeline/collision_pipeline.rs
src/pipeline/mod.rs
src/pipeline/physics_hooks.rs
src/pipeline/physics_pipeline.rs
src_testbed/harness/mod.rs
src_testbed/physics/mod.rs
src_testbed/testbed.rs

This adds the ability to modify the contact points after they are generated by the narrow-phase but before they are seen by the constraints solver. This allows the simulation of various interesting effects like conveyor belts and one-way platforms:
This can also be used for fine-grained friction and restitution coefficient modification (e.g. to simulate multiple materials on a single collider).
The contact manifold now contains a user-defined piece of data that can be updated by the contact modifier. This is useful to add some updates that depend on the previous state of the simulation (as needed by one-way platform).
The two traits for filtering intersection and contact pairs have been removed in favor of a single `PhysicsHooks` trait that combines contact filtering, proximity filtering, …

Add the ability to modify the contact points seen by the constraints solver

---

src/dynamics/rigid_body.rs
src/dynamics/solver/categorization.rs
src/dynamics/solver/position_ground_constraint.rs
src/dynamics/solver/position_ground_constraint_wide.rs
src/dynamics/solver/solver_constraints.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_wide.rs
src/dynamics/solver/velocity_ground_constraint.rs
src/dynamics/solver/velocity_ground_constraint_wide.rs
src/geometry/contact_pair.rs
src/geometry/narrow_phase.rs

This PR adds the support for dominance groups. Each rigid-body is part of a dominance group in `[-127; 127]` (the default is 0). If two rigid-body are in contact, the one with the highest dominance will act as if it has an infinite mass, making it immune to the forces the other body would apply on it. 
For example, if a dynamic body A is in the dominance group 10, and a dynamic body B in the dominance group -20, then a contact between A and B will result in A remaining immobile and B being pushed by A.
If both bodies are part of the same dominance group, then their contacts will work in the usual way (both are affected by opposite forces with the same magnitude).
A non-dynamic rigid-body is always considered as being part of a dominance group greater than any dynamic rigid-body. This …

Implement dominance groups

---

src/dynamics/integration_parameters.rs
src/dynamics/solver/joint_constraint/ball_velocity_constraint.rs
src/dynamics/solver/joint_constraint/ball_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/fixed_velocity_constraint.rs
src/dynamics/solver/joint_constraint/fixed_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint.rs
src/dynamics/solver/joint_constraint/prismatic_velocity_constraint_wide.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint.rs
src/dynamics/solver/joint_constraint/revolute_velocity_constraint_wide.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_wide.rs
src/dynamics/solver/velocity_ground_constraint.rs
src/dynamics/solver/velocity_ground_constraint_wide.rs

This PR introduces a restorative impulse in the velocity solver that aims to resolve the constraint violation. The default strength of this is zero, i.e. it is disabled.
This PR also introduces a multiplier for the velocity correction of the velocity solver. The default is `1` (keeping the old behavior).
I fixed a bug in the prismatic limit joint that used to cause violations of the conservation of momentum.
I also added support for having the prismatic joints range be zero or negative (i.e. activating both sides of the prismatic limits).
Some of the benefits of having the violation resolution in the velocity solver include:
* No need for the positional solver
* Saves some CPU time
* Saves us from potential energy violations
* Faster violation resolution
* Since we generally run the …

Optional violation correction in velocity solver

---

src/dynamics/rigid_body.rs

I think this was a bug. Related to https://github.com/dimforge/rapier/issues/132

Call update_world_mass_properties from RigidBody::set_mass_properties

---

src/dynamics/joint/joint_set.rs

`JointSet` was inadvertently left out of https://github.com/dimforge/rapier/pull/54 when `Clone` was implemented for most other types.

Derive Clone for JointSet

---

src/geometry/collider.rs

Fix https://github.com/dimforge/rapier/issues/132
This uses the `Option<Box<MassProperties>>` idea to save memory in the common case.

Per collider mass props

---

src/pipeline/query_pipeline.rs
src_testbed/testbed.rs

Currently, the only way to filter-out some colliders from a query with the `QueryPipeline` is to use an `InteractionGroups`. This group-based solution may not be flexible enough for all use-cases. This PR adds to all the queries arguments a closure that user can use to filter the colliders affected by the queries using custom rules.

Add the ability to pass a custom filter to all the QueryPipeline queries.

---

src/dynamics/rigid_body.rs

Add getters indicating if the translation or rotation dofs of a rigid-body are locked.

---

CHANGELOG.md
Cargo.toml
build/rapier2d-f64/Cargo.toml
build/rapier2d/Cargo.toml
build/rapier3d-f64/Cargo.toml
build/rapier3d/Cargo.toml
build/rapier_testbed2d/Cargo.toml
build/rapier_testbed3d/Cargo.toml
src/dynamics/ccd/toi_entry.rs
src/dynamics/mod.rs
src/geometry/collider.rs
src/pipeline/query_pipeline.rs

- Add the support of **Continuous Collision Detection** (CCD) to make sure that some fast-moving objects (chosen by the user) don't miss any contacts. This is done by using motion-clamping, i.e., each fast-moving rigid-body with CCD enabled will be stopped at the time where their first contact happen. This will result in some "time loss" for that rigid-body. This loss of time can be reduced by increasing the maximum number  of CCD substeps executed (the default being 1).
- Add the support of **collider modification**. Now, most of the characteristics of a collider can be modified after the collider has been created.
- We now use an **implicit friction cone** for handling friction, instead of a pyramidal approximation of the friction cone. This means that friction will now  behave in a …

Release v0.7.0

---

src_testbed/testbed.rs

This disables egui interactions being sent to the orbital camera if mouse events happen within egui.
i.e. scrolling on the egui doesnt affect the orbitalcamera's zoom.
This may also want to check for 
```
|| ui_context.ctx().wants_keyboard_input()
```
not sure about this.

Testbed: check if the egui context wants pointer focus, disable orbit camera if so.

---

src/geometry/collider.rs

In my case this is for creating a compound shape from a set of existing colliders.
I do find if confusing that the `Collider.shape()` method returns a `dyn Shape`, the `Collider.set_shape()` requires a `SharedShape`, but fixing this such that `shape()`  returns a SharedShape would be a breaking change. Perhaps adding a `Collider.set_shared_shape()` method and deprecating `Collider.set_shape()`?

Created a method to retrieve the SharedShape from a collider

---

src/dynamics/rigid_body.rs
src/geometry/collider.rs

I nearly forgot that `RigidBodyBuilder` and `ColliderBuilder` use `mut self` semantics in their parameters setting functions, so a `#[must_use]` seems appropriate.
Also, `RigidBodyBuilder` seemed surprisingly locked-down in terms of field visibilities compared to `ColliderBuilder`. `body_status` is set upfront from the builder's new_* constructors, and `flags` appears to be a crate-private type, so everything else was made public by this PR.
`RigidBodyBuilder` seems like it contains pretty plain data, which permits deriving Copy. Debug should be fine as well as the flags are nicely formatted by `bitflags`.
For my use-case, the builders also serve as creation templates, so having (read-)access to everything is nicer than recreation.
Please let me know if making these fields private was a …

Add #[must_use] to builders, expose more fields

---

CHANGELOG.md
build/rapier2d-f64/Cargo.toml
build/rapier2d/Cargo.toml
build/rapier3d-f64/Cargo.toml
build/rapier3d/Cargo.toml
build/rapier_testbed2d/Cargo.toml
build/rapier_testbed3d/Cargo.toml
examples2d/Cargo.toml
src/geometry/collider.rs
src/utils.rs

The user-guide has been fully rewritten and is now exhaustive! It will be uploaded soon on [rapier.rs](https://rapier.rs/) 
- A prelude has been added in order to simplify the most common imports. For example: `use rapier3d::prelude::*`
- Add `RigidBody::set_translation` and `RigidBody.translation()`.
- Add `RigidBody::set_rotation` and `RigidBody.rotation().
- Add `RigidBody::set_next_translation` for setting the next translation of a position-based kinematic body.
- Add `RigidBody::set_next_rotation` for setting the next rotation of a position-based kinematic body.
- Add kinematic bodies controlled at the velocity level: use `RigidBodyBuilder::new_kinematic_velocity_based` or
`RigidBodyType::KinematicVelocityBased`.
- Add the cargo feature `debug-disable-legitimate-fe-exceptions` that …

Release v0.9.0

---

benchmarks2d/Cargo.toml
benchmarks2d/all_benchmarks2.rs
benchmarks2d/heightfield2.rs
benchmarks3d/Cargo.toml
benchmarks3d/all_benchmarks3.rs
benchmarks3d/heightfield3.rs
benchmarks3d/trimesh3.rs
examples2d/Cargo.toml
examples2d/all_examples2.rs
examples2d/heightfield2.rs
examples2d/polyline2.rs
examples3d/Cargo.toml
examples3d/all_examples3.rs
examples3d/all_examples3_wasm.rs
examples3d/convex_decomposition3.rs
examples3d/heightfield3.rs
examples3d/trimesh3.rs
src/lib.rs

Without this, using `vector!` and `point!` won't work because they need `nalgebra` to be in scope. To avoid forcing the user to add an explicit dependency to nalgebra, this PR imports `nalgebra` in `use rapier::prelude::*`.

Add nalgebra to the prelude to make the macros work out of the box

---

src/data/coarena.rs
src/dynamics/island_manager.rs
src/dynamics/joint/joint_set.rs
src/dynamics/rigid_body_components.rs
src/dynamics/rigid_body_set.rs
src/geometry/narrow_phase.rs
src/pipeline/physics_pipeline.rs

- Make the method `JointSet::remove_joints_attached_to_rigid_body` public so that it can can be called externally for letting component-based Rapier integration call it to cleanup joints after a rigid-body removal.
- Fix a panic that could happen when the same collider is listed twice in the `removed_colliders` array.

Fix various removal issues

---

src_testbed/graphics.rs
src_testbed/lib.rs
src_testbed/objects/node.rs
src_testbed/plugin.rs
src_testbed/testbed.rs

This is the changes required to upgrade salva to rapier 0.9.
Graphics are not being rendered, this is just so that salva's FluidTestbedPlugin has access to the data it will need.

WIP: Enable plugin graphics

---

src/dynamics/joint/ball_joint.rs
src/dynamics/joint/fixed_joint.rs
src/dynamics/joint/generic_joint.rs
src/dynamics/joint/joint.rs
src/dynamics/joint/prismatic_joint.rs
src/dynamics/joint/revolute_joint.rs
src/dynamics/rigid_body_components.rs
src/geometry/collider_components.rs

I mostly need `PartialEq` on a few `RigidBody` components, but I looked at all of the other component types and tried to determine whether they could implement `Eq`, `PartialOrd`, `Ord`, and/or `Hash`. Most of the types containing `Real`s only make sense to implement `PartialEq`, but some of the other components seem to be able to implement more traits. Also added `AsMut + DerefMut` to `ColliderPosition` for convenience since the field is public anyway, and found a few more typos.
Let me know if there's anything I missed or anything I added that I shouldn't have.

Derive and impl more traits for components

---

CHANGELOG.md
benchmarks2d/joint_ball2.rs
benchmarks2d/joint_fixed2.rs
benchmarks2d/joint_prismatic2.rs
benchmarks3d/joint_ball3.rs
benchmarks3d/joint_fixed3.rs
benchmarks3d/joint_prismatic3.rs
benchmarks3d/joint_revolute3.rs
build/rapier2d-f64/Cargo.toml
build/rapier2d/Cargo.toml
build/rapier3d-f64/Cargo.toml
build/rapier3d/Cargo.toml
build/rapier_testbed2d/Cargo.toml
build/rapier_testbed3d/Cargo.toml
examples2d/joints2.rs
examples3d/debug_prismatic3.rs
examples3d/joints3.rs
src/dynamics/joint/joint_set.rs
src/pipeline/query_pipeline.rs

- Implement `Clone` for `IslandManager`.
- `JointSet::insert` no longer takes the rigid-body set in its arguments.
- Modify the testbed's plugin system to let plugins interact with the rendering.
- Implement `PartialEq` for most collider and rigid-body components.

Release v0.10.0

---

src/geometry/narrow_phase.rs

It looks like the contact graph updates unconditionally, whereas the intersection graph's edge labels only update if `ActiveEvents::INTERSECTION_EVENTS` is set. This is inconsistent and doesn't seem to be documented, so I'm guessing it wasn't intended.

Update intersection graph regardless of active_events

---

src/lib.rs

Added a pointer from the module-level cargo docs to the actual docs on `rapier.rs` so other people won't be lost like I was.
(Searches for documentation often end up on `docs.rs`, which is not where most of Rapier's docs live. The README has a pointer to the docs, but it isn't as visible once you're on `docs.rs`.)
This is the same change as pr89 for `bevy_rapier`. This one is less important since it's harder to overlook `rapier.rs` from here, but I think it doesn't hurt.
Ideally you'd be able to just include the `README.md` into the lib documentation, but I think that's still a nightly-only feature in cargo doc.

Add a pointer from `docs.rs` docs to rapier docs

---

src/dynamics/joint/ball_joint.rs

The second anchor is expressed in the second body's local space

Fix copy paste bug in ball joint docs

---

src_testbed/testbed.rs

Upstream salva upgrade changes need this to work when changing examples.

clear plugin graphics when examples changed, then clear the plugins vec

---

src/geometry/broad_phase_multi_sap/broad_phase_pair_event.rs
src/geometry/mod.rs

Otherwise it is impossible to use BroadPhase::update properly from other crates. I am actually surprised the compiler didn’t output an error about this (private type in public interface).

Make BroadPhasePairEvent and ColliderPair public.

---

CHANGELOG.md
build/rapier2d-f64/Cargo.toml
build/rapier2d/Cargo.toml
build/rapier3d-f64/Cargo.toml
build/rapier3d/Cargo.toml
build/rapier_testbed2d/Cargo.toml
build/rapier_testbed3d/Cargo.toml
src/dynamics/solver/delta_vel.rs
src/dynamics/solver/parallel_island_solver.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_element.rs
src/dynamics/solver/velocity_ground_constraint_element.rs
src/utils.rs
src_testbed/lib.rs

Check out the user-guide for the JS/Typescript bindings for rapier. It has been fully rewritten and is now exhaustive!
Check it out on [rapier.rs](https://www.rapier.rs/docs/user_guides/javascript/getting_started_js)
- Joint limits are now implemented for all joints that can support them (prismatic, revolute, and ball joints).
- Switch to  `nalgebra 0.29`.
- Fix the build of Rapier when targeting emscripten.

Release 0.11

---

src/pipeline/query_pipeline.rs

These are confusing because the documentation of the `TOI` struct specifies local space, which doesn't seem to be the case here in practice, perhaps because the "local space" in question is considered to be the entire collision world acting as a single shape.

Clarify coordinate space of TOI query results

---

src/pipeline/user_changes.rs

We don’t need to take a reference here, and it appears to break compilation on some recent nigthly version of rustc.

Remove useless ref

---

src/dynamics/joint/multibody_joint/multibody.rs
src/dynamics/joint/multibody_joint/multibody_joint.rs
src/dynamics/joint/multibody_joint/multibody_link.rs
src/dynamics/rigid_body_components.rs
src/dynamics/solver/island_solver.rs
src/dynamics/solver/velocity_solver.rs
src/pipeline/physics_pipeline.rs

This addresses most of the remaining issues with the use of multibody joints in their most general form (manually configured 6-dof joints). This does not address the issues with the angular motors that should be able to act on coupled coordinates instead of each axis individually.

Address issues with the genral-case for multibody joints

---

src/pipeline/physics_pipeline.rs

In `rapier2d::pipeline::physics_pipeline::PhysicsPipeline::interpolate_kinematic_velocities()`:
The code that handles `RigidBodyType::KinematicVelocityBased`: `rb_vel.integrate()` expects a local center of mass which is already in `rb_mprops.local_mprops.local_com`.

fix the parameter used for local center of mass

---

src/dynamics/joint/multibody_joint/multibody.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_components.rs
src/dynamics/solver/generic_velocity_constraint.rs
src/dynamics/solver/generic_velocity_constraint_element.rs
src/dynamics/solver/joint_constraint/joint_generic_velocity_constraint_builder.rs
src/dynamics/solver/joint_constraint/joint_velocity_constraint.rs
src/dynamics/solver/joint_constraint/joint_velocity_constraint_builder.rs
src/dynamics/solver/parallel_island_solver.rs
src/dynamics/solver/velocity_constraint.rs
src/dynamics/solver/velocity_constraint_element.rs
src/dynamics/solver/velocity_constraint_wide.rs
src/dynamics/solver/velocity_ground_constraint.rs
src/dynamics/solver/velocity_ground_constraint_element.rs
src/dynamics/solver/velocity_ground_constraint_wide.rs
src/dynamics/solver/velocity_solver.rs
src/pipeline/physics_pipeline.rs

This adds the ability to disable translations along the individual coordinate axes of a rigid-body.

Allow locking individual translational axes

---

src/dynamics/integration_parameters.rs

Derive `Debug` for `IntegrationParameters` as per [Rust API Guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits).
I wanted to print out the value of the `IntegrationParameters` struct that `bevy_rapier2d` begins with, but it didn't implement `Debug`.

Derive Debug for IntegrationParameters

---

src/dynamics/island_manager.rs

When a rigid body is created with `.can_sleep(false)`, the builder sets its activation thresholds to -1. However when the actual check is being made in island manager, the value of thresholds gets squared and sign is lost, allowing body to fall asleep.

Fix rigid bodies falling asleep when linear/angular threshold is negative

---

src/dynamics/joint/generic_joint.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_components.rs
src/dynamics/solver/interaction_groups.rs
src/geometry/collider.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src/pipeline/user_changes.rs

This PR ensures that the mass-properties of a rigid-body are recomputed after modifying one of its attached colliders.
These mass-properties are recomputed from the colliders, as well as the newly stored additional mass-properties given to the rigid-body during its creation with the `RigidBodyBuilder`.

Fix mass-properties update after collider change

---

CHANGELOG.md
Cargo.toml
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- Fix the simulation when the `parallel` feature is enabled.
- Fix bug where damping would not be applied properly to some bodies.
- Fix panics caused by various situations (contact or joints) involving rigid-bodies with locked translations/rotations.
- Fix bug where collider modifications (like changes of collision groups, or shape) would not wake-up their attached
rigid-body, or would not have any effect on pre-existing contacts.
- Fix the automatic update of a rigid-body’s mass properties after changing one of its attached colliders.
- Fix the broad-phase becoming potentially invalid after a change of collision groups.
- Switch to `nalgebra` 0.31.
- Switch to `parry` 0.9.
- Rename `JointHandle` to `ImpulseJointHandle`.
- Rename `RigidBodyMassPropsFlags` to `LockedAxes`.
- Rename …

Release v0.12.0

---

src/dynamics/island_manager.rs
src/dynamics/joint/impulse_joint/impulse_joint_set.rs
src/dynamics/joint/multibody_joint/multibody_joint_set.rs
src/geometry/collider_components.rs

- Rename STATIC to FIXED in the `ActiveCollisionTypes` flags.
- Rename `ImpulseJointSet::joints_with` to `::attached_joints`. Add the joint’s handle to the closure arguments.
- Add `MultibodyJointSet::attached_joints` to return all the multibody joints attached to a rigid-body.

Rename STATIC -> FIXED and joints_with -> attached_joints

---

src/pipeline/debug_render_pipeline/debug_render_pipeline.rs

This makes the default debug-render modes to be less noisy with only joints, rigid-bodies, and colliders enabled.

Adjust the defaults for the debug-renderer + add a JOINTS compound bitflag

---

src/geometry/broad_phase_multi_sap/broad_phase.rs
src/geometry/broad_phase_multi_sap/sap_layer.rs

This is an attempt to fix #349 and to fix #77 by:
- Rejecting NAN/INF AABBs in the broad-phase.
- Addressing a rounding error that could trigger a assertion, in the broad-phase.

Fix some corner cases in the broad-phase

---

src/pipeline/event_handler.rs

The current `ActiveEvents` docs mention a `handle_intersection_event()` function of the `EventHandler` trait that no longer exists. This change removes that reference from the `ActiveEvents` docs.

Update ActiveEvents Rustdoc to Remove Reference to EventHandler::handle_intersection_event()

---

examples2d/ccd2.rs
examples2d/sensor2.rs
examples3d/ccd3.rs
examples3d/sensor3.rs
src/geometry/collider.rs
src/geometry/contact_pair.rs
src/geometry/mod.rs
src/geometry/narrow_phase.rs
src/pipeline/event_handler.rs
src/pipeline/physics_pipeline.rs
src_testbed/harness/mod.rs
src_testbed/physics/mod.rs

This add force reporting to the `EventHandler` trait. Contact force events are generated whenever the sum of the magnitudes of all the forces between two colliders is greater than `Collider::contact_force_event_threshold`.
This also fix #352

Add force reporting

---

src/pipeline/mod.rs
src/pipeline/query_pipeline.rs
src_testbed/testbed.rs

This PR replaces the `groups: CollisionGroups` and `filter: impl Fn(ColliderHandle) -> bool` arguments from all the scene queries, by a single `QueryFilter` struct with more batteries included. This `QueryFilter` structure makes it easier to apply filters that are commonly used in games like:
- Excluding one particular collider from the scene query.
- Excluding all the colliders attached to one particular rigid-body from the scene query.
- Excluding all colliders attached to dynamic rigid-bodies from the scene query.
- Excluding all the sensors from the scene query.
- etc.
As such, this adds more built-in filtering rules lowering the need for the user to provide their own filtering closure.
This is of particular interest for, e.g., JS bindings, because relying on a closure can be very …

Add more options for filtering colliders in scene queries.

---

src/geometry/mod.rs

Since the direction is unit-sized, it shouldn’t be divided by the timestep length.

Fix the max_force_direction magnitude

---

CHANGELOG.md
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_components.rs
src/geometry/collider.rs
src/geometry/collider_components.rs
src/geometry/collider_set.rs
src/pipeline/physics_pipeline.rs
src/pipeline/user_changes.rs
src_testbed/physx_backend.rs

The goal of this PR is to cover a few recurrent requests regarding mass-properties of rigid-bodies and colliders:
- It is now possible to modify a collider’s density/mass-properties after its creation.
- It is now possible to specify the collider’s mass explicitly (instead of its density). In this case, the angular inertia tensor will be computed automatically (fix #203)
- When specifying a rigid-body’s additional mass, its additional angular inertia tensor will also be computed automatically based on its attached colliders. This resolves common issues users are having when setting only the additional mass not knowing that it would create an imbalance between linear and angular resistances to motion.

Improve the API for initializing/setting mass-properties

---

CHANGELOG.md
examples3d/locked_rotations3.rs
src/dynamics/rigid_body.rs

This was a common source of confusion. Users calling `rigid_body.restrict_translations(true, false, false)` would assume that it meant that the translation along the X axis would be locked. In reality, it mean the opposite: X is free, but Y and Z are locked.
This PR clarifies the situation by renaming the `restrict` methods as `set_allowed_translations` and `set_allowed_rotations`.

Rename restrict_translation/rotation to set_allowed_translation/rotation

---

examples3d/locked_rotations3.rs
src/dynamics/rigid_body.rs

This sounds better and is more consistant with our other uses of the word `enabled`.

Rename allowed_translation/rotation to enabled_translation/rotation

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src_testbed/box2d_backend.rs
src_testbed/physx_backend.rs

- Fix unpredictable broad-phase panic when using small colliders in the simulation.
- Fix collision events being incorrectly generated for any shape that produces multiple
contact manifolds (like triangle meshes).
- Fix panic in the `CollisionPipeline` if a collider is both added and removed before a call
to `CollisionPipeline::step`.
- The `RigidBodyBuilder::additional_mass` method will now result in the additional angular inertia
being automatically computed based on the shapes of the colliders attached to the rigid-body.
- Remove the deprecated methods `RigidBodyBuilder::mass`, `::principal_angular_inertia`, `::principal_inertia`.
- Remove the methods `RigidBodyBuilder::additional_principal_angular_inertia`. Use
`RigidBodyBuilder::additional_mass_properties` instead.
- The …

Release v0.14

---

src_testbed/lib.rs

This type is used in the `TestbedPlugin` trait, and having to re-define the same type alias in every crate using it seems unnecessary.

Reexport `BevyMaterial` alias

---

CHANGELOG.md
src/dynamics/rigid_body.rs
src/geometry/collider.rs

This was frequently reported as inconsistant by the community.

Make Collider::set_rotation and RigidBody::set_rotation take a rotation instead of an axis-angle.

---

src/dynamics/rigid_body.rs

Currently, the world-space mass-properties of a rigid-body is only updated when calling `PhysicsPipeline::step`. This can cause issues if the user applies a torque to a rigid-body after setting its position but before the next step. This PR fixes the problem by always updating the world-space mass-props whenever the user changes the rigid-body’s position.

Auto-update a rigid-body’s world mass-properties when the user sets their position

---

crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

I was looking for `DebugRenderPipeline` on docs.rs and ended on a 404 page when clicked on the link [here](https://docs.rs/bevy_rapier2d/latest/bevy_rapier2d/render/struct.DebugRenderContext.html#structfield.pipeline). It's simply because the related features were not enabled when building on docs.rs. This should fix it.

Enable more features when documenting on docs.rs

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- Implement `Copy` for `CharacterCollision`.
- Implement conversion (`From` trait) between `Group` and `u32`.
- Add `ColliderBuilder::trimesh_with_flags` to build a triangle mesh with specific flags controlling
its initialization.
- Rename `AABB` to `Aabb` to comply with Rust’s style guide.
- Switch to `parry 0.11`.
- Fix internal edges of 3D triangle meshes or 3D heightfields generating invalid contacts preventing
balls from moving straight.

Release v0.16.0

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src/dynamics/joint/multibody_joint/multibody.rs
src/dynamics/joint/multibody_joint/multibody_joint.rs
src/dynamics/rigid_body.rs
src/dynamics/rigid_body_components.rs
src/dynamics/solver/delta_vel.rs
src/dynamics/solver/joint_constraint/joint_generic_velocity_constraint.rs
src/lib.rs
src_testbed/debug_render.rs
src_testbed/lines/mod.rs
src_testbed/lines/render_dim.rs
src_testbed/objects/node.rs
src_testbed/testbed.rs

- Add `RigidBody::set_enabled`, `RigidBody::is_enabled`, `RigidBodyBuilder::enabled` to enable/disable a rigid-body
without having to delete it. Disabling a rigid-body attached to a multibody joint isn’t supported yet.
- Add `Collider::set_enabled`, `Collider::is_enabled`, `ColliderBuilder::enabled` to enable/disable a collider
without having to delete it.
- Add `GenericJoint::set_enabled`, `GenericJoint::is_enabled` to enable/disable a joint without having to delete it.
Disabling a multibody joint isn’t supported yet.
- Add `DynamicRayCastVehicleController`, a vehicle controller based on ray-casting and dynamic rigid-bodies (mostly
a port of the vehicle controller from Bullet physics).
- Add `RigidBody::user_force` and `RigidBody::user_torque` to read the forces or torques added by the …

Release v0.17.0

---

src/pipeline/user_changes.rs

This fixes a bug causing rigid-bodies disabled and then re-enabled to behave like a kinematic body. The mass-properties were not recomputed properly.

Fix rigid-body mass-properties being incorrect after disable/enable

---

src/dynamics/island_manager.rs
src/dynamics/rigid_body_components.rs

Currently the time before a body falls asleep cannot be changed and is set to 2 seconds. This PR allows this value to be changed in the `RigidBodyActivation` of the body.

Allow customising the time until sleep for a rigid body

---

examples2d/character_controller2.rs
src/control/character_controller.rs

- Fixes #426 
- Fixes https://github.com/dimforge/bevy_rapier/issues/301 modulo the documentation aspect
- Touched #418 and fixed it, but reverted because of jittering issues, see discussion.
- Fixes snapping to ground not triggering sometimes as described in https://github.com/dimforge/bevy_rapier/issues/301
- Fixes horizontal offset being mostly ignored and some instances of vertical offset being ignored
------
PR contents:
- Move stairs check before slope check to deal with some stopping along stairs
- Move along surface after stairs and slope checks
- Clean up some code, remove duplications
- Take offset into account in some places it was left out
- Fix ground being erroneously detected when jumping next to a wall composed of multiple triangles in 3D.

Make KinematicCharacterController move along obstacles, respect offset more and fix false positives in grounded detection

---

src/pipeline/event_handler.rs

Extremely minor typo correction.

Fix typo in `EventHandler::handle_collision_event`

---

src/control/character_controller.rs
src/pipeline/query_pipeline.rs

Resolves #465 
This change adds the `is_sliding_down_slope` field to the EffectiveCharacterMovement output struct for `move_shape` KinematicCharacterController function
This field will be true when the entity is sliding down at least one slope.
From my testing, this field will be true when sliding into a wall. So if the consumer does not want a player to move while sliding, make sure to check for that edge case.

#465 Add is_sliding_down_slope field to EffectiveCharacterMovement

---

examples3d/vehicle_controller3.rs
src/control/ray_cast_vehicle_controller.rs

These changes add a struct item to `Wheel` and `WheelDesc` to allow users to control how much lateral grip a raycast vehicle's wheel can have. Lower values [0-1) give an effect similar to sliding or drifting. Before these changes, [the effective side friction stiffness was `1.0`](https://github.com/dimforge/rapier/blob/master/src/control/ray_cast_vehicle_controller.rs#L512).
They also make `Wheel`'s `friction_slip` property public so it can be changed after wheel creation.
Also fixed a small spelling error in some doc comments in the raycast vehicle source file (`his` -> `has`).

Add Ability to Control Side-to-Side Grip / Forward Grip of Raycast Vehicle Wheels

---

CHANGELOG.md
src/dynamics/joint/spherical_joint.rs

Expose the spherical joint’s local frames more explicitly.

---

src/dynamics/rigid_body.rs
src/geometry/collider.rs

Fix the doc-links to `ColliderBuilder` and `RigidBodyBuilder` from their respective types.

Fix doc-links for `ColliderBuilder` and `RigidBodyBuilder`

---

src/pipeline/physics_pipeline.rs

This was removed in version 0.12.0
https://github.com/dimforge/rapier/blob/89e3d7650c84f96893376a79cbc120aeaeb74785/CHANGELOG.md?plain=1#L191

Delete mention of removed `PhysicsPipeline::step_generic`

---

CHANGELOG.md
src/pipeline/debug_render_pipeline/debug_render_backend.rs
src/pipeline/debug_render_pipeline/debug_render_pipeline.rs

Add a predicate to the DebugRenderBackend to filter out objects that are being rendered

---

src/pipeline/query_pipeline.rs

docs: exclude kinematic/dynamic reversed in description.

---

CHANGELOG.md
src/data/graph.rs
src/geometry/collider.rs
src/pipeline/physics_hooks.rs
src/pipeline/physics_pipeline.rs
src/pipeline/query_pipeline.rs

This makes things more clear as this abbreviation isn't known to everyone.
While the trailing period is common in French, it isn't in English (one might use "w.r.t.").
Fixes #498.

docs: Expand "wrt" to "with respect to".

---

crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml

This was only enabled in the `enhanced-determinism` feature, but it wasn't actually used in these crates.

deps: Remove unused `indexmap` dep.

---

src/dynamics/rigid_body.rs

rigidbody.lock_translations and lock_rotations methods were able to lock but not unlock.

fix lock_translations & lock_rotations doesn't work both ways

---

src/control/character_controller.rs

Adding feature-gated serialize/deserialize derives for the following structs:
- CharacterLength
- CharacterAutostep
- KinematicCharacterController
Resolves issue #506

Add serde derives to structures in the control module

---

src/dynamics/joint/generic_joint.rs

Removes inconsistency with other entities, such as rigid bodies and colliders - they all have `user_data` field. 
This field is usually used to store a pointer/handle to game/engine/etc entities associated with a rigid body/collider/joint. And the lack of `user_data` field causing troubles in Fyrox - I forced to use a hash map like `HashMap<Handle<Stuff>, JointHandle>` to bypass this issue, which has both performance and usability impact.

`user_data` for joints

---

src/control/character_controller.rs

Fixes https://github.com/dimforge/bevy_rapier/issues/413
I think that we should use the absolute value of the `up` attribute of a `KinematicCharacterController` when calculating the value of the `up_extent` and `side_extent` variables.
Concerning the `up_extent` variable, if you make the `up` attribute point downward, parry will make the app crash because of the `assert` in the `loosened` function of the `AABB` struct since the amount of loosening would be negative.
And concerning the `side_extent` variable, the value would not be the same if the `up` attribute points upward or downward.

Use the absolute value of the up attribute when calculating up_extent and side_extent

---

src/geometry/collider_components.rs

If collider was enabled and no other attributes were changed its collisions were not detected.
This was caused by `needs_broad_phase_update` function not handling the case of changed enabled status.
Fixes dimforge/bevy_rapier#435

Fix enabling disabled collider

---

src/dynamics/solver/joint_constraint/joint_generic_velocity_constraint.rs

It looks like `motor_axes` is just a mask of axes, similar to `locked_axes`. It shouldn't need to be shifted by `DIM` for these checks.

Fix check for motor constraints on angular DoF

---

src/dynamics/integration_parameters.rs
src/dynamics/joint/rope_joint.rs
src/dynamics/joint/spring_joint.rs
src/dynamics/rigid_body.rs
src/dynamics/solver/parallel_velocity_solver.rs
src/dynamics/solver/velocity_solver.rs
src_testbed/testbed.rs
src_testbed/ui.rs

#579 introduced a new non-linear velocity-based constraints solver. This PR reworks the way solver iterations are specified so that some combination of them lets us recover the old solver’s behavior. This is mostly for comparison purpose or for case where the small performance hit of the new solver isn’t acceptable to the user.
- `IntegrationParameters::num_friction_iteration_per_solver_iteration` is replaced by `IntegrationParameters::num_additional_friction_iteration`. This specifies how many extra friction iteration we want to run during the final solver iteration.
- `IntegrationParameters::num_internal_pgs_iterations` indicates how many PGS iteration needs to be run within each solver iteration. Setting this value to `4` and `IntegrationParameters::num_solver_iterations` to 1 is …

feat: rework solver parameters to make it easy to recover the old behaviors

---

src/pipeline/debug_render_pipeline/debug_render_pipeline.rs

Kinematic bodies that were moved after creation don't have their world_com mass properties re-calculated. This isn't a complete solution since I think ideally the `rb.mrprops.world_com` should be updated in that case, but fixes the debug renderer for now.

Calculate world center of mass from local com in debug renderer

---

src/dynamics/island_manager.rs
src/geometry/mod.rs
src/geometry/narrow_phase.rs
src/pipeline/collision_pipeline.rs

- Renames `NarrowPhase::contacts_with` to`contact_pairs_with`; and `intersections_with` to `intersection_pairs_with` for better clarity.
- Re-export BoundingVolume, RayCast, PointQuery, PointQueryWithLocation from parry.
Fix #574.

Narrow-phase methods renames + some re-exports

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

The main highlight of this release is the implementation of a new non-linear constraints solver for better stability
and increased convergence rates. See [#579](https://github.com/dimforge/rapier/pull/579) for additional information.
In order to adjust the number of iterations of the new solver, simply adjust `IntegrationParameters::num_solver_iterations`.
If recovering the old solver behavior is useful to you, call `IntegrationParameters::switch_to_standard_pgs_solver()`.
It is now possible to specify some additional solver iteration for specific rigid-bodies (and everything interacting
with it directly or indirectly through contacts and joints): `RigidBodyBuilder::additional_solver_iterations` and
`RigidBodyBuilder::set_additional_solver_iterations`. This allows for higher-accuracy on …

Release v0.18.0

---

CHANGELOG.md
src/pipeline/physics_pipeline.rs
src/pipeline/user_changes.rs

I ran into what I believe is a bug in which if a rigid body is changed to dynamic from kinematic, it may never end up in active dynamic set. This caused some issues including gravity not being integrated.
I believe in user changes we should add body to dynamic active if its type changed to dynamic. (And is enabled / not sleeping, the existing conditions).
I added a test to reproduce the issue. The failure seems to only occur if pipeline is stepped (at least) once after creating kinematic body, before switching to dynamic. Without the change to user_changes.rs, both conditions will fail in test.
Please let me know if I am somehow using API wrong and this is not a bug.

fix(user_changes): Fix RigidBodyType changed to Dynamic not added to active dynamic set

---

CHANGELOG.md
examples3d-f64/debug_serialized3.rs
examples3d/debug_deserialize3.rs
src/geometry/broad_phase.rs
src/geometry/broad_phase_multi_sap/broad_phase_multi_sap.rs
src/geometry/broad_phase_multi_sap/mod.rs
src/geometry/broad_phase_multi_sap/sap_axis.rs
src/geometry/broad_phase_multi_sap/sap_layer.rs
src/geometry/broad_phase_multi_sap/sap_proxy.rs
src/geometry/broad_phase_multi_sap/sap_region.rs
src/geometry/broad_phase_qbvh.rs
src/geometry/collider.rs
src/geometry/collider_components.rs
src/geometry/mod.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src_testbed/harness/mod.rs
src_testbed/physics/mod.rs

This adds the `BroadPhase` trait that can be implemented manually to provide a custom broad-phase implementation.
To avoid naming conflict, the current broad-phase was renamed to `BroadPhaseMultiSap`. The `DefaultBroadPhase` alias can be used too.
Fix #590 
Close #530

feat: add support for custom broad-phases

---

benchmarks2d/all_benchmarks2.rs

This was supposed to be a `'('`, not a `')'`.
Fixes #596.

Fix typo in clippy fix.

---

CHANGELOG.md
Cargo.toml
examples2d/character_controller2.rs
examples3d/character_controller3.rs
src/control/character_controller.rs
src/control/ray_cast_vehicle_controller.rs
src/dynamics/ccd/toi_entry.rs
src/dynamics/integration_parameters.rs
src/geometry/broad_phase.rs
src/geometry/collider.rs
src/geometry/mod.rs
src/pipeline/query_pipeline.rs

The main objective for this PR is to fix the issue where character controllers might get stuck against vertical walls.
- The kinematic character controller autostepping is now disabled by default.
- Add `KinematicCharacterController::normal_nudge_factor` used to help getting the character unstuck
due to rounding errors.
- Rename `TOI` to `ShapeCastHit`.
- Rename many fields from `toi` to `time_of_impact`.
- The `QueryPipeline::cast_shape` method now takes a `ShapeCastOptions` instead of the `max_toi`
and `stop_at_penetration` parameters. This allows a couple of extra configurations, including the
ability to have the shape-cast target a specific distance instead of actual shape overlap.
Close https://github.com/dimforge/rapier/pull/612 (proposed change was incorrect)
Fix #418
Fix #611 
Fix …

feat: character controller improvements

---

CHANGELOG.md
Cargo.toml
src/dynamics/joint/generic_joint.rs
src/dynamics/solver/joint_constraint/joint_constraint_builder.rs
src/dynamics/solver/joint_constraint/joint_generic_constraint_builder.rs
src/geometry/narrow_phase.rs

This PR attempts to fix #549
I am not 100% convenient in the correctness of this change, but it does fix the issue I was experiencing in my program. Especially the changes to `JointGenericVelocityOneBodyExternalConstraintBuilder`, since as far as I can tell this is used with multibodies, which I do not use. But I followed the same logic I did with `JointOneBodyConstraintBuilder`.
I also removed some outdated TODO comments that are no longer relevant I think.

Fix one body joints limits not being flipped

---

CHANGELOG.md
Cargo.toml
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- Fix crash when simulating a spring joint between two dynamic bodies.
- Fix kinematic bodies not being affected by gravity after being switched back to dynamic.
- Fix regression on contact force reporting from contact force events.
- Fix kinematic character controller getting stuck against vertical walls.
- Fix joint limits/motors occasionally not being applied properly when one of the attached
rigid-bodies is fixed.
- Fix an issue where contacts would be completely ignored between two convex shapes.
**Many stability improvements were added as part of this release. To see illustrations of some of these
changes, see [#625](https://github.com/dimforge/rapier/pull/625).**
- Add `RigidBody::predict_position_using_velocity` to predict the next position of the rigid-body
based only on its …

Release v0.19.0

---

CHANGELOG.md
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
examples2d/all_examples2.rs
examples2d/inverse_kinematics2.rs
examples3d/all_examples3.rs
examples3d/inverse_kinematics3.rs
src/dynamics/joint/multibody_joint/mod.rs
src/dynamics/joint/multibody_joint/multibody.rs
src/dynamics/joint/multibody_joint/multibody_ik.rs
src/dynamics/joint/multibody_joint/multibody_joint_set.rs
src/dynamics/joint/multibody_joint/multibody_link.rs
src/dynamics/rigid_body.rs
src/dynamics/solver/velocity_solver.rs
src/geometry/contact_pair.rs
src/pipeline/physics_pipeline.rs
src/utils.rs
src_testbed/lib.rs
src_testbed/mouse.rs
src_testbed/testbed.rs

This PR adds a simple jacobian-based inverse-kinematics solver to multibodies.
https://github.com/dimforge/rapier/assets/1734958/da2b17a4-3cf0-470a-ab8f-80fb876e953a
- Add `Multibody::inverse_kinematics`, `Multibody::inverse_kinematics_delta`,
and `::inverse_kinematics_delta_with_jacobian`
for running inverse kinematics on a multibody to align one its links pose to the given prescribed pose.
- Add `InverseKinematicsOption` to customize some behaviors of the inverse-kinematics solver.
- Add `Multibody::body_jacobian` to get the jacobian of a specific link.
- Add `Multibody::update_rigid_bodies` to update rigid-bodies based on the multibody links poses.
- Add `Multibody::forward_kinematics_single_link` to run forward-kinematics to compute the new pose and jacobian of a
single link without …

feat: add simple inverse-kinematics solver for multibodies

---

CHANGELOG.md
benchmarks3d/all_benchmarks3.rs
benchmarks3d/many_pyramids3.rs
src/dynamics/integration_parameters.rs
src/dynamics/solver/contact_constraint/generic_one_body_constraint.rs
src/dynamics/solver/contact_constraint/generic_two_body_constraint.rs
src/dynamics/solver/contact_constraint/one_body_constraint.rs
src/dynamics/solver/contact_constraint/one_body_constraint_simd.rs
src/dynamics/solver/contact_constraint/two_body_constraint.rs
src/dynamics/solver/contact_constraint/two_body_constraint_simd.rs
src/dynamics/solver/island_solver.rs
src/dynamics/solver/velocity_solver.rs
src/lib.rs
src_testbed/lib.rs
src_testbed/ui.rs

- The contact constraints regularization parameters have been changed from `erp/damping_ratio` to
`natural_frequency/damping_ratio`. This helps define them in a timestep-length independent way. The new variables
are named `IntegrationParameters::contact_natural_frequency` and `IntegrationParameters::contact_damping_ratio`.
- Remove an internal special-case for contact constraints on fast contacts. The doesn’t seem necessary with the substep
solver.

feat: make the constraints regularization coefficients confiugrable with angular frequency instead of explicit ERP

---

src/data/pubsub.rs

Seems unblocked since rust 1.51 (~2021)
I think chances are low that it impacts our msrv (minimum rust supported version), as rapier doesn't have such policy (https://github.com/dimforge/rapier/issues/592) ; but still important to consider, I didn't verify.

Fix trivial todo; removing a private type.

---

src_testbed/testbed.rs

Currently, the character controller example has all chances to crash if its kinematic character controller is removed with "KeyD".
it's the intended behaviour as hinted by a comment above modified line.

fix: testbed: keyD removes only dynamic bodies as intended

---

CHANGELOG.md
src/dynamics/ccd/ccd_solver.rs
src/pipeline/mod.rs
src/pipeline/query_pipeline/generators.rs
src/pipeline/query_pipeline/mod.rs
src/pipeline/query_pipeline/updaters.rs

When working on https://github.com/dimforge/rapier.rs/pull/104 ; I noticed an outdated note on the userguide, which was also teasing future features.
<details><summary>Note details</summary>
<p>
at https://rapier.rs/docs/user_guides/rust/scene_queries
> Right now, the query pipeline takes the `IslandManager` and `RigidBodySet` as arguments. These two arguments may look superfluous, especially if the colliders are not attached to rigid-bodies. Another update method that only takes a `ColliderSet` as its only argument will be added in the future.
</p>
</details> 
This PR allows to remove that note, and makes up for a more powerful API.
On its downside, passing a generic is less explicit, I tried my best to guide the user with the documentation.

Rework QueryPipeline update API to take less parameters

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-stl/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

This release introduces two new crates:
- `rapier3d-urdf` for loading URDF files into rapier3d. This will load the rigid-bodies,
colliders, and joints.
- `rapier3d-stl` for loading an STL file as a collision shape.
- Add `Multibody::inverse_kinematics`, `Multibody::inverse_kinematics_delta`,
and `::inverse_kinematics_delta_with_jacobian`
for running inverse kinematics on a multibody to align one its links pose to the given prescribed pose.
- Add `InverseKinematicsOption` to customize some behaviors of the inverse-kinematics solver.
- Add `Multibody::body_jacobian` to get the jacobian of a specific link.
- Add `Multibody::update_rigid_bodies` to update rigid-bodies based on the multibody links poses.
- Add `Multibody::forward_kinematics_single_link` to run forward-kinematics to compute the …

Release Rapier 0.20.0

---

CHANGELOG.md
src/pipeline/query_pipeline/mod.rs

Similar change to https://github.com/dimforge/rapier.js/pull/280.

fix: Fixed typo in castShape functions

---

src/pipeline/query_pipeline/mod.rs

Very small fix for a capitalization doc I stumbled upon

fix: capitalization typo in docs

---

src/control/character_controller.rs

While trying out https://github.com/dimforge/bevy_rapier/pull/476 ; I noticed I could jump when hitting walls (particularly on the junction of 2 walls).
When printing the normal dot value, I had this value in air: `1.7037166e-5` (hitting a wall perfectly perpendicular)
The current epsilon being `1.0e-5` ; [this dot check](https://github.com/Vrixyz/rapier/blob/c88e1eaf1b225e36188befab31bb24e7a2c4c69c/src/control/character_controller.rs#L522) is `true`, then `is_grounded` is `true`, and the character can jump in the example from https://github.com/dimforge/bevy_rapier/pull/476.
I think it makes sense to relax this epsilon ; alternatively we could:
- reuse the slope authorized for the character
- or really pump that value, and/or normalize it
- make it configurable
But that first fix is …

fix: character controller: walls less likely to trigger ground detection

---

CHANGELOG.md
src/dynamics/integration_parameters.rs
src/dynamics/rigid_body_set.rs
src/pipeline/physics_pipeline.rs

Fixes #659.
Bug introduced by https://github.com/dimforge/rapier/pull/635.
Disclaimer: I am **NOT** confident about the correction, but I'm confident it's the correct place to fix :).

Fix delta_time being 0 resulting in incorrect simulation

---

CHANGELOG.md
src/control/character_controller.rs
src_testbed/testbed.rs

in `solve_character_collision_impulses`, Taking ownership of the `CharacterCollision` is not necessary, it's a problem if we're storing the `CharacterCollision`s in another struct, such as https://github.com/dimforge/bevy_rapier/pull/523.
This pull request would help avoid a copy of the `CharacterCollision`.
Using a reference is compatible with an owned `Vec` and also conveys the information that elements are only read.

fix: less invasive `solve_character_collision_impulses` function

---

src/geometry/broad_phase_multi_sap/sap_region.rs

This works around #593, although I'm unsure of the root cause of the issue.

Fix `attempt to subtract with overflow` panic in `SAPRegion::update_after_subregion_removal()`

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-stl/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- Fix `NaN` values appearing in bodies translation and rotation after a simulation step with a delta time equal to
0 ([#660](https://github.com/dimforge/rapier/pull/660)).
- Fix crash in the SAP broad-phase when teleporting an object.
- Update to `nalgebra` 0.33 and `parry` 0.16.
- `solve_character_collision_impulses` collisions parameter is now an iterator over references.

Release v0.21.0

---

CHANGELOG.md
src/pipeline/debug_render_pipeline/debug_render_pipeline.rs

add radius line in debug mode for Ball 2d collider in order to visualize rotations
Closes #657

Rotation gizmo for Ball 2d collider

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
src/dynamics/joint/multibody_joint/multibody.rs
src/dynamics/joint/multibody_joint/multibody_joint_set.rs

Fix https://github.com/dimforge/bevy_rapier/issues/552.
Fix #382.

Fix occasional crashes when inserting or removing multibody links

---

src/geometry/interaction_groups.rs
src_testbed/lib.rs
src_testbed/testbed.rs

This removes an `extern crate` and a `use` so that we always call it via `bitflags::bitflags!` everywhere.

Use `bitflags!` consistently.

---

examples3d/all_examples3_wasm.rs

This is long obsolete and was removed from Rust itself in https://github.com/rust-lang/rust/pull/117338

Remove check for `target_arch = "asmjs"`

---

crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
src/lib.rs
src/pipeline/physics_pipeline.rs

Implicit features are slated to be removed in a future version of Rust (2024 edition).
Fixing this exposed 2 instances where the wrong feature was being checked for `serde` vs `serde-serialize`.

Prefer explicit features for optional deps.

---

src/lib.rs

This has been commented out since the first public release of Rapier in 2020.

Remove commented out reference to array-macro

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
src/geometry/broad_phase_multi_sap/broad_phase_multi_sap.rs
src/utils.rs

- Context: https://github.com/dimforge/bevy_rapier/pull/560.
Without that, serialization to string fails. Interesting to note `bincode` works without that.
error log:
```txt
thread 'main' panicked at bevy_rapier3d/examples/serialization.rs:30:51:
Unable to serialize `RapierContext`: Error("key must be a string", line: 0, column: 0)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `serialization::print_physics`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```
After more testing, I realize this crash doesn't happen every time 😮 ; around once in 10 runs 🤔.
The solution for this issue is more involved than I thought, serde json doesn't support non-string keys for `Hashmap`: …

Fix string serialization for broadphase multisap

---

crates/rapier3d-urdf/src/lib.rs
src/geometry/broad_phase_multi_sap/broad_phase_multi_sap.rs
src/lib.rs

These will be enabled in Rust 1.80 by default.

clippy: Fix `clippy::lazy_doc_continuation` lints

---

src/utils.rs

These show up when the `serde_serialize` feature is enabled.

Fix `rustdoc::broken_intra_doc_links`

---

src_testbed/lib.rs
src_testbed/testbed.rs

This code has been here but not used for a long time. There's no log feature (or dependency) within the testbed crates.

testbed: Remove use of missing log feature

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-stl/Cargo.toml
crates/rapier3d-stl/src/lib.rs
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src_testbed/testbed.rs

- Fix crash when removing a multibody joint, or a rigid-body with a multipody-joint attached to it.
- Fix crash when inserting multibody joints in an arbitrary order (instead of incrementally from root to leaf).
- Fix `BroadphaseMultiSap` not being able to serialize correctly with serde_json.
- Implement rotation gizmo for Ball 2D shape (as radius line) in Debug renderer if `DebugRenderMode::COLLIDER_SHAPES`
enabled
- Implement `Debug` for `ColliderSet`, `InteractionGraph`,
`MultibodyLink`, `MultibodyJointSet`, `Multibody`, `ImpulseJointSet`
- Update parry to v0.17. Refer to [its changelog](https://github.com/dimforge/parry/blob/master/CHANGELOG.md#v0170) for
further details.
- Divided by two the value of each `QueryFilterFlags` variant so that
the smallest one is 1 instead of 2 (fixes a …

Release v0.22.0

---

.github/workflows/rapier-ci-build.yml

This is my version of what's in #694 for CI, but only that, and using the same set of features that docs.rs uses.

ci: Enable same features as docs.rs in cargo doc

---

src/pipeline/debug_render_pipeline/debug_render_style.rs

@Vrixyz This happened when you modified one of my PRs to add links for the `Aabb` and the `cargo doc` improvements weren't in place yet to pick it up at that time. (Using merge queues would improve this...)

Fix intradoc link to fix CI.

---

examples2d/character_controller2.rs
examples3d/character_controller3.rs
src_testbed/testbed.rs

It's currently difficult to assess if character controller ground detection works correctly, this adds a visual helper (the capsule turns red when not grounded) to detect it more quickly in the examples.
https://github.com/user-attachments/assets/f0a5b817-4563-46db-a6fe-16d5433d91b3
<details><summary>ground detection analysis</summary>
<p>
when calling `colliders_with_aabb_intersecting_aabb` from within `detect_grounded_status_and_apply_friction`
, it sometimes doesn't get any manifests, resulting in `grounded = false`.
- Honestly, a raycast down is probably less work than fiddling with nudge factor, numerical errors, shape implementations and whatnot 🤔 
- Or maybe just exposing or bumping up the predict ground distance around https://github.com/dimforge/rapier/blob/661c33f64c5a3392f5abb8a …

Color visualization for grounded character controller

---

Cargo.toml
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src/lib.rs
src_testbed/lib.rs

By using `workspace.lints`, we can configure lints once for everything (and then inherit it into the various crates).
The lint configuration for `unexpected_cfgs` works in 1.80+ and warns otherwise.

Use workspace lints to control unexpected_cfgs.

---

CHANGELOG.md
src/geometry/interaction_groups.rs

Currently the default is to being a member of all groups with a filter/interaction with everything.
I believe this is a bit backwards and makes special interactions between groups harder to understand/deal with without flipping all of your logic to be a "non-membership" or by modifying the interaction groups of every object in your simulation.
This is more in line with what Box2d (one membership, all filter) and Godot (one membership, one filter) do currently, ~however there are counterexamples like Unity (all membership, all filter) and the current default.~ Unity is actually one membership/all filter as well since they do not allow multiple groups to be selected, however they allow configuring the default interactions/filters.
There is also an argument of all filter vs one filter as the …

Use a reserved "Default" layer for memberships in `InteractionGroups`

---

src/control/character_controller.rs

- in https://github.com/dimforge/rapier/pull/446 ; there had been a lot of experimentation on that offset. this `1.1` has been kept since the creation of the character controller.
- I think that 1.1 is not enough, I'm not sure exactly why there's number approximation this high, but manual testing results in better behaviour (no red controller from https://github.com/dimforge/rapier/pull/705), and automatic testing still passes.
offset is `CharacterLength::Relative(0.01)`, then the height of the `CharacterController` in the exampple is `0.3`, resulting in an exxaggerated  offset (for aabb computation) of  `0.0033`. The nudge factor being `0.0001` shouldn´t impact that, but we're still in small numbers game. I think overshooting a bit won´t hurt much, especially if it fixes `is_grounded` …

fix character controller is_grounded 

---

CHANGELOG.md
src/counters/collision_detection_counters.rs
src/counters/mod.rs
src/data/coarena.rs
src/dynamics/joint/multibody_joint/multibody_joint_set.rs

These are ones not found by `typos` for various reasons.

Fix more typos.

---

CHANGELOG.md
src/geometry/broad_phase_multi_sap/sap_layer.rs

related to https://github.com/dimforge/rapier/pull/675.
needed for https://github.com/dimforge/bevy_rapier/pull/560
We should probably make a test for these, but I'm not sure how easy it is to build these up.

Fix string serialization for broadphase multisap (regions)

---

Cargo.toml
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- Detected on https://github.com/dimforge/rapier/pull/727/
I realized the copying of cargo.toml incurs a compilation error as they're not part of a workspace anymore while publishing, this pull request sets the lints in each crate.

Workspace lints in each crate.

---

CHANGELOG.md
examples3d/vehicle_joints3.rs
src/dynamics/joint/impulse_joint/impulse_joint_set.rs
src/dynamics/joint/multibody_joint/multibody_joint_set.rs
src/pipeline/physics_pipeline.rs

follow up to https://github.com/dimforge/rapier/issues/692

ImpulseJointSet::get_mut option to wake up connected bodies

---

CHANGELOG.md
src/dynamics/rigid_body_set.rs
src/geometry/collider_set.rs

These allow an application to reduce the cost of reallocation when they know that a large number of colliders or rigid bodies will be created.

Improve capacity handling for `ColliderSet`, `RigidBodySet`.

---

.github/workflows/rapier-ci-build.yml
src/geometry/broad_phase_multi_sap/broad_phase_multi_sap.rs
src/geometry/broad_phase_multi_sap/sap_layer.rs
src/pipeline/physics_pipeline.rs

- Fix #739
- The regression was introduced by https://github.com/dimforge/rapier/pull/716

fix compilation for feature enhanced-determinism

---

src/geometry/collider.rs

There were some typos in `collider.rs` ("along along the y axis").
I removed the second along and capitalized Y to be more coherent with `src/dynamics/rigid_body_components.rs` (but I didn't add the various ` the latter has, I can do it if you want me to).

Fixed some typos.

---

CONTRIBUTING.md

Fixes the previously misleading link under the JavaScript/TypeScript contribution guidelines from `rapier.rs` -> `rapier.js`

Fixed typo in link in CONTRIBUTING.md

---

CHANGELOG.md
Cargo.toml
benchmarks3d/trimesh3.rs
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-meshloader/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d-urdf/src/lib.rs
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
examples2d/Cargo.toml
examples2d/all_examples2.rs
examples2d/debug_intersection2.rs
examples2d/trimesh2.rs
examples3d/Cargo.toml
examples3d/debug_trimesh3.rs
examples3d/dynamic_trimesh3.rs
examples3d/trimesh3.rs
src/geometry/collider.rs
src/geometry/mesh_converter.rs
src/pipeline/query_pipeline/mod.rs
src_testbed/testbed.rs
src_testbed/ui.rs

- Follow up to https://github.com/dimforge/parry/pull/273#issuecomment-2496130758
- blocked by https://github.com/dimforge/parry/pull/293
- Waiting for a parry release
See following trace with example 2d 100 x 100 balls:
- :yellow_square: this trace is master (traverse_best_first)
- :red_square: external trace is this PR (traverse_depth_first)

Parry update (0.18?)

---

examples3d/debug_shape_modification3.rs
src_testbed/graphics.rs
src_testbed/testbed.rs

This PR is for a fix for the `GraphicsManager::remove_collider_nodes` function in the testbed. The problem was that the entity was despawned but not removed from `GraphicsManager::b2sn`, creating an invalid state. See [this thread](https://discord.com/channels/507548572338880513/1246940826332958801) for the discussion.
`TestbedApp::add_callback` still requires a manual refresh with `gfx.add_collider` if the user wants to see the 3D entity update correctly.
```rust
if let Some(gfx) = &mut gfx {
gfx.remove_collider(ball_coll_handle, &physics.colliders);
gfx.add_collider(ball_coll_handle, &physics.colliders);
}
```
`debug_shape_modification3` before:
`debug_shape_modification3` after:

Fix shape modification not updating graphics in testbed

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-meshloader/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml

- The broad-phase region key has been replaced by an i64 in the f64 version of rapier, increasing the range before panics occur.
- Fix `BroadphaseMultiSap` not being able to serialize correctly with serde_json.
- Fix `KinematicCharacterController::move_shape` not respecting parameters `max_slope_climb_angle` and `min_slope_slide_angle`.
- Improve ground detection reliability for `KinematicCharacterController`. (#715)
- Fix wasm32 default values for physics hooks filter to be consistent with native: `COMPUTE_IMPULSES`.
- `RigidBodySet` and `ColliderSet` have a new constructor `with_capacity`.
- Use `profiling` crate to provide helpful profiling information in different tools.
- The testbeds have been updated to use `puffin_egui`
- `InteractionGroups` default value for `memberships` is now …

Release v0.23.0

---

src/pipeline/debug_render_pipeline/debug_render_backend.rs
src/pipeline/debug_render_pipeline/debug_render_pipeline.rs
src/pipeline/debug_render_pipeline/debug_render_style.rs
src_testbed/debug_render.rs

This PR aims to fix issue: https://github.com/dimforge/rapier/issues/370
I have tested these changes according to the [contribution guide](https://github.com/dimforge/rapier/blob/master/CONTRIBUTING.md) and did not find anything unusual.
Please let me know if there are other things that i need to consider as well :)

Removed hardcoded values for DebugColor in various places

---

crates/rapier3d-meshloader/CHANGELOG.md
crates/rapier3d-meshloader/Cargo.toml
crates/rapier3d-urdf/CHANGELOG.md
crates/rapier3d-urdf/Cargo.toml

The currently published version (0.3.0) still relies on rapier 0.22 instead of 0.23.

Release rapier3d-meshloader v0.4.0

---

CHANGELOG.md
src/geometry/contact_pair.rs
src/geometry/narrow_phase.rs

- Follow up to #734
This PR adds 2 tests: 1 for each scenario.

Incorrect narrow_phase collisions after using ColliderSet::set_parent

---

.gitignore
benchmarks2d/all_benchmarks2.rs
benchmarks3d/all_benchmarks3.rs
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
examples2d/Cargo.toml
examples2d/all_examples2.rs
examples2d/s2d_pyramid.rs
examples3d-f64/Cargo.toml
examples3d-f64/all_examples3-f64.rs
examples3d/Cargo.toml
examples3d/all_examples3.rs
examples3d/all_examples3_wasm.rs
src_testbed/camera2d.rs
src_testbed/camera3d.rs
src_testbed/graphics.rs
src_testbed/lib.rs
src_testbed/save.rs
src_testbed/settings.rs
src_testbed/testbed.rs
src_testbed/ui.rs

Improve the ergonomics of the rapier testbed by:
- Automatically saving the example selection, camera position, example settings, etc. and restore them when starting the testbed app again.
- Add support for per-example settings. For example in the video below, the number of cubes in the pyramid can be controlled (this the only example modified to use that new feature for now):
https://github.com/user-attachments/assets/eefc7356-39c1-428c-870c-0cbeba57a2e0

feat(rapier_testbed): autosave testbed configuration + add support for per-example settings

---

CHANGELOG.md
examples2d/utils/character.rs
examples3d/utils/character.rs
src/control/pid_controller.rs
src/dynamics/rigid_body_components.rs

Fix typo introduced in #804 and ensure `AxesMask::LIN_Z` is only usable in 3D.

feat: rename AxisMask to AxesMask + enable LIN_Z only in 3D

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml

- Add `PdController` and `PidController` for making it easier to control dynamic rigid-bodies at the velocity level.
This can for example be used as a building block for a dynamic character controller.
- Add `RigidBodyPosition::pose_errors` to compute the translational and rotational delta between
`RigidBodyPosition::position` and `::next_position`.
- Implement `Sub` for `RigidBodyVelocity`.
- Add `RigidBody::local_center_of_mass()` to get its center-of-mass in the rigid-body’s local-space.
_NOTE: The changes on the testbed are breaking changes, so we need to wait for rapier 0.24 to release it to keep the version numbers in sync._

Release v0.23.1

---

src/dynamics/coefficient_combine_rule.rs
src/geometry/narrow_phase.rs

- Follow up to https://github.com/dimforge/rapier/pull/741#discussion_r1843723816

Use enum variants rather than casting to u8 for comparisons

---

src/data/mod.rs
src/data/modified_objects.rs
src/dynamics/mod.rs
src/dynamics/rigid_body_components.rs
src/dynamics/rigid_body_set.rs
src/geometry/collider_set.rs
src/geometry/mod.rs
src/pipeline/collision_pipeline.rs
src/pipeline/physics_pipeline.rs
src/pipeline/user_changes.rs

Fix #802
Note: Fixing those + adding tests is a good first step but we should thrive for making those mistakes more difficult to make altogether.

Fix user changes handling

---

src/dynamics/island_manager.rs
src/dynamics/solver/interaction_groups.rs

Prevent underflow with saturating_sub(1) (#812)

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-meshloader/Cargo.toml
crates/rapier3d-meshloader/src/lib.rs
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d-urdf/src/lib.rs
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src/pipeline/event_handler.rs

This is a pretty small release. Bumping the minor version because of the dependencies updates.
- `IntegrationParameters` now implements `PartialEq`.
- Update dependencies (including `parry` 0.19).

Release v0.24.0

---

CHANGELOG.md
src/geometry/mesh_converter.rs

Now that `VHACDParameters` is `Copy` in parry 0.19, this can now be fixed here.

Make `MeshConverter` enum derive `Copy`

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d-meshloader/Cargo.toml
crates/rapier3d-urdf/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
examples2d/voxels2.rs
examples3d/voxels3.rs
src/dynamics/rigid_body_components.rs
src/geometry/broad_phase_qbvh.rs
src/geometry/collider.rs
src/geometry/mod.rs
src_testbed/graphics.rs
src_testbed/harness/mod.rs
src_testbed/objects/node.rs
src_testbed/physics/mod.rs
src_testbed/testbed.rs

- Update to parry 0.21.0. This changes the initialization of `Voxels` colliders by removing the primitive geometry argument.
- This also fixes intersection checks with voxels, and force calculation between voxels and other voxels or compound shapes.

Release d0.26.0

---

CHANGELOG.md
crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
src/dynamics/rigid_body_set.rs
src/geometry/collider_set.rs

- Add `RigidBodySet::get_pair_mut` and `ColliderSet::get_pair_mut` to get two mutable rigid-bodies or colliders
simultaneously.

Release v0.26.1

---

src/counters/timer.rs

rapier3d failed to compile for wasm32 with the `profiler` feature flag enabled.
This PR fixes it, making the `profiler` flag work as expected across any target_arch.

Fix web_time usage for Timer

---

examples2d/character_controller2.rs
examples2d/rope_joints2.rs
examples2d/utils/character.rs
examples3d/character_controller3.rs
examples3d/rope_joints3.rs
examples3d/utils/character.rs
src_testbed/ui.rs

To help with reproducing different character controller setups, speed and gravity are useful knobs to tweak in the testbed.
originally to help with https://discordapp.com/channels/507548572338880513/747935665076830259/1361598634357035238.

Testbed: add gravity control + character controller speed control

---

examples2d/debug_intersection2.rs
examples2d/utils/character.rs
examples3d/utils/character.rs
src/control/character_controller.rs
src/dynamics/ccd/ccd_solver.rs
src/pipeline/query_pipeline.rs

- Spawned from https://github.com/dimforge/bevy_rapier/pull/671
- functions returning iterators are difficult to build on top of those if they capture references.
- QueryPipeline (especially Mut) should be passed as reference as much as possible

Changed some API to be more library friendly

---

crates/rapier2d-f64/Cargo.toml
crates/rapier2d/Cargo.toml
crates/rapier3d-f64/Cargo.toml
crates/rapier3d/Cargo.toml
crates/rapier_testbed2d-f64/Cargo.toml
crates/rapier_testbed2d/Cargo.toml
crates/rapier_testbed3d-f64/Cargo.toml
crates/rapier_testbed3d/Cargo.toml
src/lib.rs
src/pipeline/event_handler.rs
src_testbed/harness/mod.rs
src_testbed/physics/mod.rs

Replaced all uses of `crossbeam::channel` with `std::sync::mpsc` to reduce the dependency footprint.
- Modified channel imports from `crossbeam::channel::{Sender, Receiver}` to `std::sync::mpsc::{Sender, Receiver}`
- Changed `crossbeam::channel::unbounded()` to `std::sync::mpsc::channel()`
- Removed `crossbeam = "0.8"` dependency from 8 Cargo.toml files
- Removed `pub extern crate crossbeam;` from src/lib.rs
- Updated doc comments to remove crossbeam mentions
As discussed in #828, crossbeam is only used for its channel implementation. Since std::sync::mpsc provides equivalent functionality for this use case, we can use the standard library instead.
Fixes #828

Replace crossbeam channel with std::sync::mpsc
