- .github/workflows/rapier-ci-bench.yml
This fixes the benchmark message action in our CI.
> Use environment file to set environment variables.

- .github/workflows/rapier-ci-build.yml
- src_testbed/testbed.rs
This was not checked by the CI before.
> Fix compilation of the testbed when the parallel feature is enabled.

- examples2d/add_remove2.rs
- examples2d/platform2.rs
- examples2d/sensor2.rs
- examples3d/debug_add_remove_collider3.rs
- examples3d/debug_dynamic_collider_add3.rs
- examples3d/debug_rollback3.rs
- examples3d/fountain3.rs
- examples3d/platform3.rs
- examples3d/sensor3.rs
- src_testbed/harness/mod.rs
- src_testbed/harness/plugin.rs
- src_testbed/plugin.rs
- src_testbed/testbed.rs
- src_testbed/ui.rs
This moves some of the code from testbed, and delegates it to the harness.
There may be some mistakes, as the logic for benchmarking, & running in a window are delicate. 
If you want, I can look at moving the benchmark code to a separate crate, so it can be removed from testbed.
Cheers
> Harness testbed integration

- src/pipeline/physics_pipeline.rs
An alternative fix is to always have serde enabled for tests
> fix cargo test -p rapier3d

- src/dynamics/rigid_body.rs
This was helpful when diagnosing https://github.com/dimforge/rapier/issues/97
I figure it is up to the caller to include or ignore non-dynamic bodies.
> Add functions for kinetic and potential energy of a RigidBody

- src/dynamics/rigid_body.rs
I also improved the documentation for the various force/impulse applying functions.
> Replace linacc/angacc with force/torque inside of RigidBody

- src/dynamics/joint/joint_set.rs
Fix https://github.com/dimforge/rapier/issues/121
> Add JointSet::get_mut and get_unknown_gen_mut

- CHANGELOG.md
- Cargo.toml
- benchmarks2d/Cargo.toml
- benchmarks3d/Cargo.toml
- build/rapier2d-f64/Cargo.toml
- build/rapier2d/Cargo.toml
- build/rapier3d-f64/Cargo.toml
- build/rapier3d/Cargo.toml
- build/rapier_testbed2d/Cargo.toml
- build/rapier_testbed3d/Cargo.toml
- examples2d/Cargo.toml
- examples3d/Cargo.toml
See the Changelogs for details.
> Release v0.6.0

- src/geometry/contact_pair.rs
Solver contacts need to be serialized too, otherwise some contact data are lost during one frame when waking up sleeping bodies.
> Fix determinism issue after restoring a snapshot.

- build/rapier_testbed2d/Cargo.toml
- build/rapier_testbed3d/Cargo.toml
- src/dynamics/rigid_body.rs
> Fix missing sqrt when setting the angular inertia of a RigidBodyBuilder

- build/rapier2d-f64/Cargo.toml
- build/rapier2d/Cargo.toml
- build/rapier3d-f64/Cargo.toml
- build/rapier3d/Cargo.toml
- build/rapier_testbed3d/Cargo.toml
There may be others, but my go-to tool for this `cargo +nightly udeps` doesn't work at the moment due to the current build-issue.
> Remove unused dependency

- build/rapier3d-f64/Cargo.toml
- build/rapier3d/Cargo.toml
- examples2d/one_way_platforms2.rs
- examples3d/all_examples3.rs
- examples3d/debug_friction3.rs
- examples3d/one_way_platforms3.rs
- src/dynamics/coefficient_combine_rule.rs
- src/dynamics/solver/delta_vel.rs
- src/dynamics/solver/mod.rs
- src/dynamics/solver/velocity_constraint.rs
- src/dynamics/solver/velocity_constraint_element.rs
- src/dynamics/solver/velocity_constraint_wide.rs
- src/dynamics/solver/velocity_ground_constraint.rs
- src/dynamics/solver/velocity_ground_constraint_element.rs
- src/dynamics/solver/velocity_ground_constraint_wide.rs
- src/geometry/contact_pair.rs
- src/pipeline/physics_hooks.rs
- src/utils.rs
- src_testbed/physx_backend.rs
See https://github.com/dimforge/rapier/issues/137#issuecomment-790818496 for details on the problem this PR solves.
Fix #137.
> Projection friction impulses on an implicit cone instead of a pyramid approximation.

- ARCHITECTURE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> Add ARCHITECTURE, CODE_OF_CONDUCT, CONTRIBUTING files + flesh out the README

- src/dynamics/ccd/ccd_solver.rs
- src/geometry/collider_set.rs
- src/pipeline/physics_pipeline.rs
> Fix crash caused by a collider being remove before the first timestep.

- examples3d/all_examples3.rs
- examples3d/debug_prismatic3.rs
- examples3d/joints3.rs
- src/dynamics/solver/joint_constraint/prismatic_velocity_constraint.rs
> Fix torque generation for the prismatic joint motor

- src/geometry/broad_phase_multi_sap/broad_phase.rs
- src/geometry/broad_phase_multi_sap/sap_region.rs
> Fix crash in broad-phase after shape modification.

- src/dynamics/island_manager.rs
- src/geometry/collider.rs
`Clone` police here :laughing: Since `IslandManager` implements `Serialize`/`Deserialize`, I'm assuming it should also implement `Clone`. 
Also fixed a random typo I found.
> Derive Clone for IslandManager

- .github/workflows/rapier-ci-build.yml
- src/dynamics/solver/velocity_constraint_element.rs
- src/dynamics/solver/velocity_ground_constraint_element.rs
> Fix emscripten build + add emscripten build to the CI

- build/rapier2d-f64/Cargo.toml
- build/rapier2d/Cargo.toml
- build/rapier3d-f64/Cargo.toml
- build/rapier3d/Cargo.toml
- examples2d/add_remove2.rs
- src/dynamics/rigid_body_components.rs
- src/geometry/broad_phase_multi_sap/broad_phase.rs
- src/geometry/broad_phase_multi_sap/sap_layer.rs
- src/pipeline/physics_pipeline.rs
- src_testbed/harness/mod.rs
- src_testbed/plugin.rs
- src_testbed/testbed.rs
- Fix situations where large moving collider could miss some collisions because of a broad-phase bug.
- Fix the incorrect estimation of velocity for position-based kinematic bodies.
> Fix some position-based kinematic bodies issues

- src/data/arena.rs
- src/data/graph.rs
- src/dynamics/joint/fixed_joint.rs
- src/dynamics/joint/multibody_joint/multibody.rs
- src/dynamics/joint/multibody_joint/multibody_joint_set.rs
- src/dynamics/joint/spherical_joint.rs
- src/dynamics/rigid_body_components.rs
- src/dynamics/solver/delta_vel.rs
- src/dynamics/solver/joint_constraint/joint_generic_velocity_constraint.rs
- src/geometry/broad_phase_multi_sap/broad_phase_pair_event.rs
- src/geometry/collider_components.rs
- src/geometry/narrow_phase.rs
Fix #218 
Just added several defaults methods
> add defaults for the several structs

- src/dynamics/solver/velocity_solver.rs
Fix https://github.com/dimforge/bevy_rapier/issues/118
> Fix the application of damping to bodies part of an active island

- .vscode/tasks.json
- src/geometry/broad_phase_multi_sap/broad_phase.rs
The following example could make the simulation crash. This is caused by a stray `return` that wasn’t transformed to a `continue;` when switching from a closure to a loop..
```rust
use rapier3d::prelude::*;
use rapier_testbed3d::Testbed;
pub fn init_world(testbed: &mut Testbed) {
let mut bodies = RigidBodySet::new();
let mut colliders = ColliderSet::new();
let impulse_joints = ImpulseJointSet::new();
let multibody_joints = MultibodyJointSet::new();
// Character controller.
let body = RigidBodyBuilder::kinematic_position_based()
.translation(vector![1.4591663825619798, 1.375, -2.1640342585282166])
.additional_mass(10.0);
let collider = ColliderBuilder::cuboid(0.5, 0.5, 0.5)
.active_events(ActiveEvents::all())
.active_collision_types(ActiveCollisionTypes::all());
let character = …
```
> Fix broad-phase becomming potentially invalid after collision group change

- src/geometry/narrow_phase.rs
> Fix incorrect sensor events being generated after collider removal

- src/geometry/mod.rs
- src/pipeline/event_handler.rs
- src_testbed/physics/mod.rs
> Name the contact force events ContactForceEvent instead of CollisionForceEvent

- src/dynamics/joint/generic_joint.rs
- src/geometry/mod.rs
- src/pipeline/event_handler.rs
- src/pipeline/query_pipeline.rs
This also fixes a few comments here and there.
> Add hepler function for building a contact force event from a contact pair

- examples2d/collision_groups2.rs
- examples3d/collision_groups3.rs
- src/geometry/interaction_groups.rs
- src/geometry/mod.rs
> bitflags for InteractionGroups

- CHANGELOG.md
- crates/rapier2d-f64/Cargo.toml
- crates/rapier2d/Cargo.toml
- crates/rapier3d-f64/Cargo.toml
- crates/rapier3d/Cargo.toml
- examples2d/all_examples2.rs
- examples2d/character_controller2.rs
- examples3d/all_examples3.rs
- examples3d/character_controller3.rs
- examples3d/newton_cradle3.rs
- src/control/character_controller.rs
- src/control/mod.rs
- src/lib.rs
- src/pipeline/query_pipeline.rs
- src_testbed/testbed.rs
This adds a first implementation of a character controller. The character controller currently supports the following features:
- Slide on uneven terrains
- Interaction with dynamic bodies.
- Climb stairs automatically.
- Automatically snap the body to the floor when going downstairs.
- Prevent sliding up slopes that are too steep
- Prevent sliding down slopes that are not steep enough
- Interactions with moving platforms.
- Report information on the obstacles it hit on its path.
> Add a character controller implementation

- CHANGELOG.md
- crates/rapier2d-f64/Cargo.toml
- crates/rapier2d/Cargo.toml
- crates/rapier3d-f64/Cargo.toml
- crates/rapier3d/Cargo.toml
- crates/rapier_testbed2d-f64/Cargo.toml
- crates/rapier_testbed2d/Cargo.toml
- crates/rapier_testbed3d-f64/Cargo.toml
- crates/rapier_testbed3d/Cargo.toml
- Add a **kinematic character** controller implementation. See the `control` module. The character controller currently
supports the following features:
- Slide on uneven terrains
- Interaction with dynamic bodies.
- Climb stairs automatically.
- Automatically snap the body to the floor when going downstairs.
- Prevent sliding up slopes that are too steep
- Prevent sliding down slopes that are not steep enough
- Interactions with moving platforms.
- Report information on the obstacles it hit on its path.
- Implement `serde` serialization/deserialization for `CollisionEvents` when the `serde-serialize` feature is enabled
- The methods `Collider::set_rotation`, `RigidBody::set_rotation`, and `RigidBody::set_next_kinematic_rotation` now
take a rotation (`UnitQuaternion` or `UnitComplex`) …
> Release v0.15.0

- src/control/character_controller.rs
> Fixed typos in character_controller.rs

- examples2d/all_examples2.rs
- examples2d/rope_joints2.rs
- examples3d/rope_joints3.rs
Fix CI build error in PR (see #429)
> Fix CI build error check-fmt

- CHANGELOG.md
- src/dynamics/rigid_body.rs
My first rust commit, a very small addition to get the strengths/torques added by the user.
> Adds methods to retrieve forces added by the user.

- src/dynamics/rigid_body.rs
> Fix docs for method setting kinematic translation/rotation

- src_testbed/testbed.rs
Steps to reproduce the bug before this fix:
1. Start testbed
2. Switch to character controller example
3. Press D
4. Crash
> Prevent testbed.rs from crashing when pressing D

- examples3d/all_examples3.rs
- examples3d/debug_multibody_ang_motor_pos3.rs
- examples3d/spherical_joint_testing.rs
- src/dynamics/joint/multibody_joint/multibody_joint.rs
I included the reproduction code posted in issue #416 as an example just to make testing this solution a bit easier.
> Fix #416 Update spherical joint motor position

- CHANGELOG.md
- src/dynamics/solver/contact_constraint/contact_constraints_set.rs
- src/dynamics/solver/joint_constraint/joint_constraint_builder.rs
- src/dynamics/solver/joint_constraint/joint_velocity_constraint.rs
> Implement linear-coupled-motor constraint between two dynamic bodies

- CHANGELOG.md
- src/dynamics/rigid_body.rs
> feat: add RigidBody::predict_position_using_velocity

- CHANGELOG.md
- src/dynamics/rigid_body.rs
- src/geometry/collider.rs
> feat: add RigidBody::copy_from and Collider::copy_from

- CHANGELOG.md
- src/dynamics/solver/contact_constraint/generic_one_body_constraint.rs
- src/dynamics/solver/contact_constraint/generic_two_body_constraint.rs
- src/dynamics/solver/contact_constraint/one_body_constraint.rs
- src/dynamics/solver/contact_constraint/one_body_constraint_element.rs
- src/dynamics/solver/contact_constraint/one_body_constraint_simd.rs
- src/dynamics/solver/contact_constraint/two_body_constraint.rs
- src/dynamics/solver/contact_constraint/two_body_constraint_element.rs
- src/dynamics/solver/contact_constraint/two_body_constraint_simd.rs
Address https://github.com/dimforge/rapier.js/issues/261
> Fix reported contact impulse in the contact force event

- crates/rapier_testbed2d-f64/Cargo.toml
- crates/rapier_testbed2d/Cargo.toml
- crates/rapier_testbed3d-f64/Cargo.toml
- crates/rapier_testbed3d/Cargo.toml
- examples3d/vehicle_joints3.rs
- src_testbed/camera2d.rs
- src_testbed/camera3d.rs
- src_testbed/debug_render.rs
- src_testbed/graphics.rs
- src_testbed/objects/node.rs
- src_testbed/plugin.rs
- src_testbed/testbed.rs
This also improves the way materials are created to leverage bevy’s auto-instancing more consistently.
> feat: update testbeds to bevy 0.13

- CHANGELOG.md
- src/control/character_controller.rs
- src_testbed/testbed.rs
https://github.com/dimforge/rapier.rs/pull/104 will have to adapt to this modification
> Character controller: change solve_character_collision_impulses to take multiple CharacterCollision

- CHANGELOG.md
- src/pipeline/query_pipeline/mod.rs
- Fixes https://github.com/dimforge/rapier.js/issues/275
> Fix QueryFilterFlags values having a bitshift too much

- src_testbed/testbed.rs
> Update flags for testbed

- .typos.toml
Improvements
- check hidden files, typos works on the filesystem (not on git index)
- add context to "PN" (used only once)
- order items alphabetically
> Improve typos configuration

- src/dynamics/joint/revolute_joint.rs
> Fix Nans from RevoluteJoint::angle()

- src/dynamics/joint/impulse_joint/impulse_joint_set.rs
- src/dynamics/joint/multibody_joint/multibody_joint_set.rs
- src/pipeline/physics_pipeline.rs
- Follow up to https://github.com/dimforge/rapier/pull/716#discussion_r1758457207
> Use hashset from parry (#716 follow up)

- scripts/publish-testbeds.sh
- Fixes https://github.com/dimforge/rapier/issues/750
> publish f64 version of testbed

- CHANGELOG.md
- src/dynamics/integration_parameters.rs
- To help with reflecting remote types from bevy: https://github.com/dimforge/bevy_rapier/pull/639
> Add partialeq to integrationparameters

- CHANGELOG.md
- crates/rapier2d-f64/Cargo.toml
- crates/rapier2d/Cargo.toml
- crates/rapier3d-f64/Cargo.toml
- crates/rapier3d/Cargo.toml
- crates/rapier_testbed2d-f64/Cargo.toml
- crates/rapier_testbed2d/Cargo.toml
- crates/rapier_testbed3d-f64/Cargo.toml
- crates/rapier_testbed3d/Cargo.toml
- examples2d/voxels2.rs
- examples3d/voxels3.rs
- src/dynamics/ccd/toi_entry.rs
- src/dynamics/joint/spherical_joint.rs
- src_testbed/objects/node.rs
The version of parry 0.20.0 got yanked and some minor adjustment to the testbed were needed as a result.
> Update to parry 0.20.1
